---
title: Airspace
timezone: UTC
collections:
  board-members:
    title: Board Members
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: board-members
  values:
    author: ''
    category: ''
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: A free HTML5 agency template
url: https://comh.cf/
baseurl: 
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
